spring:
  profiles: app
tucker:
  security:
     oauth2:
        clients[0]:
          clientId: tucker
          clientSecret: tucker
          accessTokenValiditySeconds: 3600
        clients[1]:
          clientId: bobo
          clientSecret: bobo
          #accessTokenValiditySeconds: 7200
        jwtSigningKey: tucker
