spring:
  profiles: core

tucker:
  security:
    code:
      sms:
        length: 5
        expireIn: 61
        url: /test
  social:
    qq:
      app-id:
      app-secret:
      providerId: /callback.do
    weiChat:
      app-id:
      app-secret:
    filterProcessesUrl: /qqLogin