spring:
  profiles: core

  redis:
    host: 188.131.254.195
    port: 6379

tucker:
  security:
    code:
      sms:
        length: 5
        expireIn: 61
        url: /test
  social:
    qq:
      app-id:
      app-secret:
      providerId: /callback.do
    weiChat:
      app-id:
      app-secret:
    filterProcessesUrl: /qqLogin
