spring:
  profiles: browser

  session:
    store-type: REDIS
    timeout: 600

tucker:
   security:
     browser:
       LoginPage: /login.html
       loginType: REDIRECT
       LogoutPage: /logout.html
       rememberMeSeconds: 3601
     code:
        image:
          length: 4
          url: /user
          width: 67
          height: 23
          expireIn: 61
